services:
  obscreen:
    image: obscreen/obscreen:latest
    pull_policy: always
    container_name: obscreen
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./obscreen.lic:/app/obscreen.lic
      - ./data:/app/data
#      - ./license-local.key:/app/license-local.key # see more: https://docs.obscreen.io/features/offline.html
    network_mode: host
    environment:
      PORT: 5000
      SECRET_KEY: ANY_SECRET_KEY_HERE
