services:
  obscreen:
    image: obscreen/obscreen:latest
    pull_policy: always
    container_name: obscreen
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./license:/app/license
      - ./data:/app/data
      # Uncomment next line if you want one-click button update on GUI
      #- /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    environment:
      PORT: 5000
      SECRET_KEY: ANY_SECRET_KEY_HERE
    ports:
      - 5000:5000
